/**
 * AUTO-GENERATED by i18nprune — do not edit the marked regions by hand unless you understand the risks.
 * The "i18nprune:generated" block is replaced whenever locales are added/removed via patching.
 * Optional custom code may live in the "i18nprune:user" block (preserved across regenerations).
 * Import this module from app code (or a small optional wrapper) to use lazy locale JSON bundles.
 */

// i18nprune:generated:start
const LOCALE_REGISTRY = [
  {
    "code": "en",
    "englishName": "English",
    "nativeName": "English",
    "direction": "ltr"
  },
  {
    "code": "ar",
    "englishName": "Arabic",
    "nativeName": "العربية",
    "direction": "rtl"
  },
  {
    "code": "fr",
    "englishName": "French",
    "nativeName": "français",
    "direction": "ltr"
  }
] as const;
export type LocaleMeta = { code: string; englishName: string; nativeName: string; direction: 'ltr' | 'rtl' };
export type LocaleCode = LocaleMeta['code'];
const DEFAULT_LOCALE_CODE: LocaleCode = "en";

type LocaleCodesInput = string | readonly string[];
export type GetLocalesResult = { ok: true; locales: LocaleMeta[] } | { ok: false; locales: []; error: string; missing: string[] };
export type GetDefaultLocaleCodeResult = LocaleCode;
export type GetLocaleResult = LocaleMeta | undefined;
export type LoadLocaleMessagesOk = { ok: true; code: LocaleCode; messages: LocaleMessages };
export type LoadLocaleMessagesErr = { ok: false; code: string; error: string };
export type LoadLocaleMessagesResult = LoadLocaleMessagesOk | LoadLocaleMessagesErr;
export type LoadLocaleMessagesPromise = Promise<LoadLocaleMessagesResult>;

export type LocaleMessages = Record<string, unknown>;
type LocaleLoader = () => Promise<{ default: LocaleMessages }>;
type ConfigJsonShape = { locales?: unknown };

/** Lazy JSON importers — paths are relative to this file. */
const localeLoaders: Partial<Record<string, LocaleLoader>> = {
  "en": () => import("../../locales/en.json"),
  "ar": () => import("../../locales/ar.json"),
  "fr": () => import("../../locales/fr.json"),
};

function parseLocaleMetaList(input: unknown): LocaleMeta[] | null {
  if (!Array.isArray(input)) return null;
  const parsed: LocaleMeta[] = [];
  for (const row of input) {
    if (!row || typeof row !== 'object') return null;
    const candidate = row as Record<string, unknown>;
    const code = typeof candidate.code === 'string' ? candidate.code : null;
    const englishName = typeof candidate.englishName === 'string' ? candidate.englishName : null;
    const nativeName = typeof candidate.nativeName === 'string' ? candidate.nativeName : null;
    const direction = candidate.direction === 'ltr' || candidate.direction === 'rtl' ? candidate.direction : null;
    if (!code || !englishName || !nativeName || !direction) return null;
    parsed.push({ code, englishName, nativeName, direction });
  }
  return parsed;
}

let localeRegistryCache: LocaleMeta[] | null = null;
let localeRegistryPromise: Promise<LocaleMeta[]> | null = null;

async function readLocaleRegistry(): Promise<LocaleMeta[]> {
  if (localeRegistryCache) return localeRegistryCache;
  if (!localeRegistryPromise) {
    localeRegistryPromise = (async (): Promise<LocaleMeta[]> => {
      try {
        const mod = (await import('./config.json')) as ConfigJsonShape | { default?: ConfigJsonShape };
        const cfg = (mod as { default?: ConfigJsonShape }).default ?? (mod as ConfigJsonShape);
        const parsed = parseLocaleMetaList(cfg?.locales);
        if (!parsed || parsed.length === 0) return [...LOCALE_REGISTRY] as LocaleMeta[];
        localeRegistryCache = parsed;
        return parsed;
      } catch {
        return [...LOCALE_REGISTRY] as LocaleMeta[];
      }
    })();
  }
  return localeRegistryPromise;
}

export async function getDefaultLocaleCode(): Promise<GetDefaultLocaleCodeResult> {
  const locales = await readLocaleRegistry();
  const fallback = locales[0]?.code;
  return fallback ?? DEFAULT_LOCALE_CODE;
}

export async function getLocales(codes?: LocaleCodesInput): Promise<GetLocalesResult> {
  const locales = await readLocaleRegistry();
  if (codes == null) return { ok: true, locales: [...locales] };
  const requested = Array.isArray(codes) ? [...new Set(codes)] : [codes];
  const found = locales.filter((row) => requested.includes(row.code));
  const missing = requested.filter((code) => !found.some((row) => row.code === code));
  if (missing.length > 0) return { ok: false, locales: [], error: `Unknown locale code(s): ${missing.join(', ')}`, missing };
  return { ok: true, locales: found };
}

export async function getLocale(code: string): Promise<GetLocaleResult> {
  const locales = await readLocaleRegistry();
  return locales.find((row) => row.code === code);
}

export async function loadLocaleMessages(code: string): LoadLocaleMessagesPromise {
  if (!(await getLocale(code))) return { ok: false, code, error: `Unsupported locale code: ${code}` };
  const loader = localeLoaders[code];
  if (!loader) return { ok: false, code, error: `No loader configured for locale: ${code}` };
  try {
    const mod = await loader();
    return { ok: true, code, messages: mod.default };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { ok: false, code, error: `Failed to load locale "${code}": ${msg}` };
  }
}
// i18nprune:generated:end

// i18nprune:user:start
// Optional: add small helpers or re-exports here.

// i18nprune:user:end
