/* eslint-disable */
// AUTO-GENERATED by apps/web/scripts/generate-site-data.ts — do not edit by hand.
// Regenerate: pnpm --filter i18nprune-web run generate:data

export const SITE_DATA = {
  "generatedAt": "2026-04-14T09:38:39.515Z",
  "gitHub": {
    "owner": "zamdevio",
    "repo": "i18nprune",
    "cloneUrlHttps": "https://github.com/zamdevio/i18nprune.git",
    "stars": null,
    "forks": null,
    "openIssues": null,
    "watchers": null,
    "contributors": null,
    "apiError": "GitHub repo HTTP 404"
  },
  "git": {
    "commitCount": 16,
    "headBranch": "main",
    "recentCommits": [
      {
        "shortHash": "a212227",
        "subject": "chore(docs): sync new exports docs to nextra/content"
      },
      {
        "shortHash": "48edf28",
        "subject": "chore(constants): centralize CLI_NAME and CONFIG_BASE_NAME"
      },
      {
        "shortHash": "ee5c32e",
        "subject": "chore: update gitignore"
      },
      {
        "shortHash": "c4e1c1a",
        "subject": "chore(nextra): add documentation site app and synced content"
      },
      {
        "shortHash": "051cc7a",
        "subject": "chore: add languages catalog generator script"
      },
      {
        "shortHash": "1e9e527",
        "subject": "test: add integration tests and sample i18n fixture app"
      }
    ]
  },
  "tests": {
    "allPassed": true,
    "success": true,
    "testFiles": 44,
    "totalTests": 147,
    "passedTests": 147,
    "failedTests": 0,
    "pendingTests": 0
  },
  "workspace": {
    "pnpmWorkspaceProjects": 5
  }
} as const;

export type SiteData = typeof SITE_DATA;
