export {
  clampTranslateMaxWorkers,
  configSchema,
  ConfigValidationError,
  DEFAULT_CONFIG,
  defineConfig,
  loadCoreConfigFromPath,
  localesFilesystemSchema,
  mergeCoreConfigInputs,
  mergePartialConfigIntoBase,
  collectLocalesFilesystemConfigWarnings,
  classifyLocalesSourceInput,
  issueLocalesSourceNotInBundle,
  resolveSourceLocaleAbsoluteFromRelPaths,
  resolveSourceLocaleAbsolutePath,
  validateLocalesSourceConfigValue,
  parseI18nPruneConfig,
  REFERENCE_POLICY_SAFE_DEFAULTS,
  resolveCoreConfig,
  resolveCoreConfigLayers,
  resolveTranslateConfig,
  tryLoadCoreConfigFromPath,
} from '../config/index.js';
