export {
  analyzePatchingState,
  applyPatchPlanAtomic,
  buildPatchPlan,
  buildPatchingSectionIncompleteDiagnostic,
  composeLoadersGeneratedFile,
  detectPatchingRecipe,
  patchingBlockPresent,
  resolvePatchingConfigLocales,
  renderGeneratedInnerBlock,
  runPatching,
} from '../patching/index.js';
export type {
  LocaleConfigMismatch,
  PatchingAction,
  PatchingAnalyzeOutput,
  PatchingCommandName,
  PatchingConfigInput,
  PatchingDiagnostic,
  PatchingFileEdit,
  PatchingLocaleRecord,
  PatchingMode,
  PatchingPlan,
  PatchingRecipeId,
  PatchingResult,
  PatchingRunInput,
  PatchingRuntimePorts,
  PatchingSkipReason,
  RepairPatchingConfigLocalesResult,
  ResolvePatchingLocalesResult,
  ResolvedPatchingConfig,
} from '../types/patching/index.js';
