import type { PatchingLocaleRecord } from '../types/patching/index.js';
import { normalizeLanguageCode } from '../shared/languages/normalize.js';
import {
  GENERATED_MODULE_END,
  GENERATED_MODULE_START,
  GENERATED_USER_END,
  GENERATED_USER_START,
} from './constants.js';

const FILE_HEADER = `/**
 * AUTO-GENERATED by i18nprune — do not edit the marked regions by hand unless you understand the risks.
 * The "i18nprune:generated" block is replaced whenever locales are added/removed via patching.
 * Optional custom code may live in the "i18nprune:user" block (preserved across regenerations).
 * Import this module from app code (or a small optional wrapper) to use lazy locale JSON bundles.
 */
`;

function jsonImportPath(importBase: string, code: string): string {
  const base = importBase.replace(/\/+$/, '').replace(/\\/g, '/');
  return `${base}/${code}.json`;
}

/** Machine-owned block only (between generated markers in the output file). */
export function renderGeneratedInnerBlock(params: {
  records: readonly PatchingLocaleRecord[];
  importBase: string;
  defaultLocaleCode?: string;
}): string {
  const { records, importBase } = params;
  const codes = records.map((r) => r.code);
  const preferred = params.defaultLocaleCode ? normalizeLanguageCode(params.defaultLocaleCode) : undefined;
  const defaultCode = preferred && codes.includes(preferred) ? preferred : (codes[0] ?? 'en');
  const registryJson = JSON.stringify(records, null, 2);

  const loaderEntries = records
    .map((r) => `  ${JSON.stringify(r.code)}: () => import(${JSON.stringify(jsonImportPath(importBase, r.code))}),`)
    .join('\n');

  return [
    `const LOCALE_REGISTRY = ${registryJson} as const;`,
    `export type LocaleMeta = { code: string; englishName: string; nativeName: string; direction: 'ltr' | 'rtl' };`,
    `export type LocaleCode = LocaleMeta['code'];`,
    `const DEFAULT_LOCALE_CODE: LocaleCode = ${JSON.stringify(defaultCode)};`,
    ``,
    `type LocaleCodesInput = string | readonly string[];`,
    `export type GetLocalesResult = { ok: true; locales: LocaleMeta[] } | { ok: false; locales: []; error: string; missing: string[] };`,
    `export type GetDefaultLocaleCodeResult = LocaleCode;`,
    `export type GetLocaleResult = LocaleMeta | undefined;`,
    `export type LoadLocaleMessagesOk = { ok: true; code: LocaleCode; messages: LocaleMessages };`,
    `export type LoadLocaleMessagesErr = { ok: false; code: string; error: string };`,
    `export type LoadLocaleMessagesResult = LoadLocaleMessagesOk | LoadLocaleMessagesErr;`,
    `export type LoadLocaleMessagesPromise = Promise<LoadLocaleMessagesResult>;`,
    ``,
    `export type LocaleMessages = Record<string, unknown>;`,
    `type LocaleLoader = () => Promise<{ default: LocaleMessages }>;`,
    `type ConfigJsonShape = { locales?: unknown };`,
    ``,
    `/** Lazy JSON importers — paths are relative to this file. */`,
    `const localeLoaders: Partial<Record<string, LocaleLoader>> = {`,
    loaderEntries,
    `};`,
    ``,
    `function parseLocaleMetaList(input: unknown): LocaleMeta[] | null {`,
    `  if (!Array.isArray(input)) return null;`,
    `  const parsed: LocaleMeta[] = [];`,
    `  for (const row of input) {`,
    `    if (!row || typeof row !== 'object') return null;`,
    `    const candidate = row as Record<string, unknown>;`,
    `    const code = typeof candidate.code === 'string' ? candidate.code : null;`,
    `    const englishName = typeof candidate.englishName === 'string' ? candidate.englishName : null;`,
    `    const nativeName = typeof candidate.nativeName === 'string' ? candidate.nativeName : null;`,
    `    const direction = candidate.direction === 'ltr' || candidate.direction === 'rtl' ? candidate.direction : null;`,
    `    if (!code || !englishName || !nativeName || !direction) return null;`,
    `    parsed.push({ code, englishName, nativeName, direction });`,
    `  }`,
    `  return parsed;`,
    `}`,
    ``,
    `let localeRegistryCache: LocaleMeta[] | null = null;`,
    `let localeRegistryPromise: Promise<LocaleMeta[]> | null = null;`,
    ``,
    `async function readLocaleRegistry(): Promise<LocaleMeta[]> {`,
    `  if (localeRegistryCache) return localeRegistryCache;`,
    `  if (!localeRegistryPromise) {`,
    `    localeRegistryPromise = (async (): Promise<LocaleMeta[]> => {`,
    `      try {`,
    `        const mod = (await import('./config.json')) as ConfigJsonShape | { default?: ConfigJsonShape };`,
    `        const cfg = (mod as { default?: ConfigJsonShape }).default ?? (mod as ConfigJsonShape);`,
    `        const parsed = parseLocaleMetaList(cfg?.locales);`,
    `        if (!parsed || parsed.length === 0) return [...LOCALE_REGISTRY] as LocaleMeta[];`,
    `        localeRegistryCache = parsed;`,
    `        return parsed;`,
    `      } catch {`,
    `        return [...LOCALE_REGISTRY] as LocaleMeta[];`,
    `      }`,
    `    })();`,
    `  }`,
    `  return localeRegistryPromise;`,
    `}`,
    ``,
    `export async function getDefaultLocaleCode(): Promise<GetDefaultLocaleCodeResult> {`,
    `  const locales = await readLocaleRegistry();`,
    `  const fallback = locales[0]?.code;`,
    `  return fallback ?? DEFAULT_LOCALE_CODE;`,
    `}`,
    ``,
    `export async function getLocales(codes?: LocaleCodesInput): Promise<GetLocalesResult> {`,
    `  const locales = await readLocaleRegistry();`,
    `  if (codes == null) return { ok: true, locales: [...locales] };`,
    `  const requested = Array.isArray(codes) ? [...new Set(codes)] : [codes];`,
    `  const found = locales.filter((row) => requested.includes(row.code));`,
    `  const missing = requested.filter((code) => !found.some((row) => row.code === code));`,
    `  if (missing.length > 0) return { ok: false, locales: [], error: \`Unknown locale code(s): \${missing.join(', ')}\`, missing };`,
    `  return { ok: true, locales: found };`,
    `}`,
    ``,
    `export async function getLocale(code: string): Promise<GetLocaleResult> {`,
    `  const locales = await readLocaleRegistry();`,
    `  return locales.find((row) => row.code === code);`,
    `}`,
    ``,
    `export async function loadLocaleMessages(code: string): LoadLocaleMessagesPromise {`,
    `  if (!(await getLocale(code))) return { ok: false, code, error: \`Unsupported locale code: \${code}\` };`,
    `  const loader = localeLoaders[code];`,
    `  if (!loader) return { ok: false, code, error: \`No loader configured for locale: \${code}\` };`,
    `  try {`,
    `    const mod = await loader();`,
    `    return { ok: true, code, messages: mod.default };`,
    `  } catch (err) {`,
    `    const msg = err instanceof Error ? err.message : String(err);`,
    `    return { ok: false, code, error: \`Failed to load locale "\${code}": \${msg}\` };`,
    `  }`,
    `}`,
  ].join('\n');
}

export function extractUserIsland(existingFileText: string): string {
  const s = existingFileText.indexOf(GENERATED_USER_START);
  const e = existingFileText.indexOf(GENERATED_USER_END);
  if (s >= 0 && e > s) {
    return existingFileText.slice(s + GENERATED_USER_START.length, e).replace(/^\n+/, '').replace(/\n+$/, '');
  }
  return '// Optional: add small helpers or re-exports here.\n';
}

export function composeLoadersGeneratedFile(innerBlock: string, userIsland: string): string {
  const body = [
    FILE_HEADER.trimEnd(),
    '',
    GENERATED_MODULE_START,
    innerBlock.trimEnd(),
    GENERATED_MODULE_END,
    '',
    GENERATED_USER_START,
    userIsland.trimEnd(),
    '',
    GENERATED_USER_END,
    '',
  ].join('\n');
  return `${body.endsWith('\n') ? body : `${body}\n`}`;
}

export function extractExistingDefaultLocaleCode(existingFileText: string): string | undefined {
  const match = existingFileText.match(
    /const\s+DEFAULT_LOCALE_CODE\s*=\s*(["'])(?<code>[A-Za-z0-9_-]+)\1/,
  );
  const code = match?.groups?.code?.trim();
  return code ? normalizeLanguageCode(code) : undefined;
}
