import { PROJECT_REPORT_KIND, PROJECT_REPORT_SCHEMA_VERSION } from './constants.js';

export type ProjectReportSummary = {
  missingKeysCount: number;
  dynamicSitesCount: number;
  keyObservationsCount: number;
  /**
   * Source files scanned under `project.srcRoot` (same scope as key-site and dynamic scans).
   * Omitted in older embedded JSON.
   */
  sourceFilesScannedCount?: number;
  /** True when every scanned literal key exists in the source locale JSON. */
  ok: boolean;
};

/** Where `i18nprune report` ran; drives stable editor deep links in the HTML UI. */
export type ProjectReportEnvironment = {
  platform: string;
  arch: string;
  nodeVersion: string;
  osRelease: string;
  distro?: string;
  /** Set when the scan ran inside WSL (`WSL_DISTRO_NAME`). Required for `linux-wsl` → Windows editor UNC paths. */
  wslDistroName?: string;
  /**
   * Distinguishes native Linux from WSL. Omitted in older reports (inferred from `wslDistroName` when possible).
   */
  runtimeFamily?: 'windows' | 'darwin' | 'linux' | 'linux-wsl';
};

export type ProjectReportProjectMeta = {
  cwd: string;
  sourceLocalePath: string;
  localesDir: string;
  srcRoot: string;
  sourceLocaleTag?: string;
  /** Present when generated by a recent CLI; older JSON may omit this. */
  environment?: ProjectReportEnvironment;
};

export type ProjectReportDocument = {
  kind: typeof PROJECT_REPORT_KIND;
  schemaVersion: typeof PROJECT_REPORT_SCHEMA_VERSION;
  generatedAt: string;
  toolVersion: string;
  project: ProjectReportProjectMeta;
  summary: ProjectReportSummary;
  details: {
    missingKeys: string[];
    dynamicSites: unknown[];
    keyObservations: unknown[];
  };
};
