/**
 * Manual VitePress sidebar (srcDir: content, cleanUrls: true).
 * Folder links like /commands/validate map to index.md; leaf pages e.g. /cli/cache.
 */
import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Config['sidebar'] = {
  '/': [
    {
      text: 'Start Here',
      items: [
        { text: 'Documentation home', link: '/' },
        { text: 'Onboarding hub', link: '/onboarding/' },
        { text: 'CLI path', link: '/onboarding/cli' },
        { text: 'SDK path', link: '/onboarding/sdk' },
        { text: 'CI path', link: '/onboarding/ci' },
        { text: 'Hosted surfaces', link: '/onboarding/hosted' },
        { text: 'Contributors', link: '/contributors/' },
        { text: 'Workflow (local dev)', link: '/workflow' },
      ],
    },
    {
      text: 'CLI',
      collapsed: true,
      items: [
        { text: 'CLI overview', link: '/cli/' },        
        { text: 'CLI disk cache', link: '/cli/cache' },
        { text: 'Runtime overview', link: '/runtime/' },
        { text: 'Verbosity (quiet / silent)', link: '/cli/verbosity' },
        { text: 'Prompts', link: '/cli/prompts' },
        { text: 'JSON output (--json)', link: '/cli/json' },
        {
          text: 'Commands',
          collapsed: true,
          items: [
            { text: 'Commands hub', link: '/commands/' },
            { text: 'init', link: '/commands/init' },
            { text: 'config', link: '/commands/config' },
            { text: 'doctor', link: '/commands/doctor' },
            { text: 'validate', link: '/commands/validate' },
            { text: 'sync', link: '/commands/sync' },
            { text: 'report', link: '/commands/report' },
            { text: 'missing', link: '/commands/missing' },
            { text: 'generate', link: '/commands/generate' },
            { text: 'locales', link: '/commands/locales/' },
            { text: 'locales list', link: '/commands/locales/list' },
            { text: 'locales dynamic', link: '/commands/locales/dynamic' },
            { text: 'locales delete', link: '/commands/locales/delete' },
            { text: 'share', link: '/commands/share/' },
            { text: 'languages', link: '/commands/languages' },
            { text: 'providers', link: '/commands/providers' },
            { text: 'cleanup', link: '/commands/cleanup' },
            { text: 'quality', link: '/commands/quality' },
            { text: 'review', link: '/commands/review' },
            { text: 'help', link: '/commands/help' },
          ],
        },
      ],
    },
    {
      text: 'Configuration & I/O',
      collapsed: true,
      items: [
        { text: 'Configuration', link: '/config/' },
        { text: 'Locales config', link: '/config/locales' },
        { text: 'Translation', link: '/config/translate' },
        { text: 'Exclude (scan scope)', link: '/config/exclude' },
        { text: 'Environment variables', link: '/config/env' },
        { text: 'Cache config', link: '/config/cache' },
        { text: 'Patching config', link: '/config/patching' },
        { text: 'Policies', link: '/config/policies' },
      ],
    },
    {
      text: 'Architecture',
      collapsed: true,
      items: [
        { text: 'Architecture hub', link: '/architecture/' },
        { text: 'Project tree layout', link: '/architecture/tree' },
        { text: 'Extractor overview', link: '/architecture/extraction/' },
        { text: 'Dynamic keys', link: '/architecture/extraction/dynamic' },
        { text: 'Regex & limits', link: '/architecture/extraction/regex' },
        { text: 'ADR 001 - CLI scope', link: '/architecture/decisions/001-scope-v0-1' },
        { text: 'ADR 002 - Translation call config', link: '/architecture/decisions/002-configurable-translation-calls' },
        { text: 'ADR 003 - Loader integration (opt-in)', link: '/architecture/decisions/003-user-i18n-loader-integration' },
        { text: 'ADR 004 - Auto-patch (opt-in)', link: '/architecture/decisions/004-auto-patch' },
        { text: 'ADR 005 - Dynamic key rebuild', link: '/architecture/decisions/005-dynamic-key-rebuild-and-prefix' },
        { text: 'ADR 006 - Command orchestrator boundary', link: '/architecture/decisions/006-command-orchestrator-boundary' },
        { text: 'ADR 007 - CLI JSON envelope', link: '/architecture/decisions/007-cli-json-envelope-contract' },
        { text: 'ADR 008 - Cache ownership', link: '/architecture/decisions/008-cache-ownership-and-host-boundary' },
        { text: 'ADR 009 - Share snapshot contract', link: '/architecture/decisions/009-share-hosted-snapshot-contract' },
        { text: 'ADR 010 - Locale layout and metadata', link: '/architecture/decisions/010-locale-layout-and-metadata-modes' },
        { text: 'ADR 011 - Runtime-neutral host model', link: '/architecture/decisions/011-runtime-neutral-sdk-host-model' },
      ],
    },
    {
      text: 'Runtime, SDK, and translators',
      collapsed: true,
      items: [
        { text: 'Runtime overview', link: '/runtime/' },
        { text: 'Node / CLI runtime', link: '/runtime/node' },
        { text: 'Browser runtime', link: '/runtime/web' },
        { text: 'Worker / edge runtime', link: '/runtime/worker' },
        { text: 'SDK operations', link: '/sdk/operations' },
        { text: 'Translator engine', link: '/translator/' },
      ],
    },
    {
      text: 'Issues reference',
      collapsed: true,
      items: [
        { text: 'Issues hub', link: '/issues/' },
        { text: 'CLI issues', link: '/issues/cli' },
        { text: 'Cleanup issues', link: '/issues/cleanup' },
        { text: 'Config issues', link: '/issues/config' },
        { text: 'Context issues', link: '/issues/context' },
        { text: 'Doctor issues', link: '/issues/doctor' },
        { text: 'Generate issues', link: '/issues/generate' },
        { text: 'I/O issues', link: '/issues/io' },
        { text: 'Languages issues', link: '/issues/languages' },
        { text: 'Locale issues', link: '/issues/locale' },
        { text: 'Locales issues', link: '/issues/locales' },
        { text: 'Missing issues', link: '/issues/missing' },
        { text: 'Patching issues', link: '/issues/patching' },
        { text: 'Path issues', link: '/issues/paths' },
        { text: 'Quality issues', link: '/issues/quality' },
        { text: 'Report issues', link: '/issues/report' },
        { text: 'Scan issues', link: '/issues/scan' },
        { text: 'Sync issues', link: '/issues/sync' },
        { text: 'Translate issues', link: '/issues/translate' },
        { text: 'Validate issues', link: '/issues/validate' },
        { text: 'Project issues', link: '/issues/project' },
        { text: 'Share issues', link: '/issues/share' },
      ],
    },
    {
      text: 'Examples',
      collapsed: true,
      items: [
        { text: 'Examples hub', link: '/examples/' },
        { text: 'jq cookbook', link: '/examples/jq-cookbook' },
        { text: 'SDK examples', link: '/examples/sdk' },
      ],
    },
    {
      text: 'Patching & translators',
      collapsed: true,
      items: [
        { text: 'Patching overview', link: '/patching/' },
        { text: 'Loader integration', link: '/patching/loader' },
        { text: 'Patching config', link: '/patching/config' },
      ],
    },
    {
      text: 'Release & maintenance',
      collapsed: true,
      items: [
        { text: 'Release notes (portal)', link: 'https://releases.i18nprune.dev' },
        { text: 'Update checks & version throttle', link: '/cli/cache' },
      ],
    },
    {
      text: 'Edge cases & barriers',
      collapsed: true,
      items: [
        { text: 'Edge cases', link: '/edge-cases/' },
        { text: 'Solved', link: '/edge-cases/solved/' },
        { text: 'Sync metadata flags', link: '/edge-cases/solved/sync-metadata-flag-conflict' },
        { text: 'Generate --resume', link: '/edge-cases/solved/generate-resume-partial-run-contract' },
        { text: 'Share hash dedup', link: '/edge-cases/solved/share-hash-dedup-and-force-replace' },
        { text: 'Layout mismatch rebuild', link: '/edge-cases/solved/locale-layout-mismatch-rebuild' },
        { text: 'CI non-interactive', link: '/edge-cases/solved/ci-noninteractive-confirmation-gates' },
        { text: 'CLI json parity', link: '/edge-cases/solved/cli-json-command-parity' },
        { text: 'Per-file const maps', link: '/edge-cases/solved/per-file-const-map' },
        { text: 'Unsolved', link: '/edge-cases/unsolved/' },
        { text: 'Unsolved inventory', link: '/edge-cases/unsolved/inventory' },
        { text: 'Unsolved policy framework', link: '/edge-cases/unsolved/policy-framework' },
        { text: 'Extraction limits', link: '/architecture/extraction/' },
        { text: 'Contributors', link: '/contributors/' },
      ],
    },
  ],
}
