import { assertSyncPortResult } from '../../runtime/helpers/sync/index.js';
import { readJsonFileWithLimit, textByteLength, writeJsonAtomic } from '../../cache/io/helpers.js';
import { ISSUE_SHARE_JSON_REPAIRED, ISSUE_SHARE_JSON_WRITE_FAILED } from '../../shared/constants/issueCodes.js';
import type { CacheRuntime } from '../../types/cache/index.js';
import type { Issue } from '../../types/json/envelope/index.js';
import type { ShareCacheEntry, ShareJsonFile, ShareJsonHealKind, ShareJsonHealReport, LoadShareJsonResult } from '../../types/share/index.js';
import { shareJsonFileSchema } from '../schema.js';

export const SHARE_JSON_BASENAME = 'share.json' as const;

/** Default max bytes for `share.json` reads (generous; entries are small). */
export const DEFAULT_MAX_SHARE_JSON_BYTES = 512 * 1024;

function emptyShareFile(): ShareJsonFile {
  return { version: 1, entries: [] };
}

function healReport(): ShareJsonHealReport {
  return { repaired: false, actions: [], details: [] };
}

function pushHeal(heal: ShareJsonHealReport, kind: ShareJsonHealKind, detail: string): void {
  heal.repaired = true;
  heal.actions.push(kind);
  heal.details.push(detail);
}

function shareJsonRepairedIssue(heal: ShareJsonHealReport, sharePath: string): Issue {
  const suffix = heal.details.length > 0 ? `\n\n${heal.details.join('\n')}` : '';
  return {
    severity: 'warning',
    code: ISSUE_SHARE_JSON_REPAIRED,
    message:
      `share.json was missing or invalid — i18nprune repaired it automatically. Do not edit this file by hand; use \`i18nprune share list\` / \`share delete\` instead.${suffix}`,
    path: sharePath,
  };
}

/**
 * Resolves `{projectDir}/share.json` using the host path port.
 */
export function resolveShareJsonPath(projectDir: string, path: { join: (...parts: string[]) => string }): string {
  return path.join(projectDir, SHARE_JSON_BASENAME);
}

function entryDedupeKey(e: ShareCacheEntry): string {
  const id = e.kind === 'project' ? e.workerProjectId ?? '' : e.workerReportId ?? '';
  return `${e.kind}\0${e.workerBaseUrl}\0${id}`;
}

/**
 * Merges duplicate worker rows (same kind + base URL + worker id), keeping the newest `lastUsedAt`.
 */
export function mergeDuplicateShareEntries(entries: ShareCacheEntry[]): { entries: ShareCacheEntry[]; merged: number } {
  const byKey = new Map<string, ShareCacheEntry>();
  let merged = 0;
  for (const e of entries) {
    const key = entryDedupeKey(e);
    const prev = byKey.get(key);
    if (!prev) {
      byKey.set(key, e);
      continue;
    }
    merged += 1;
    if (e.lastUsedAt > prev.lastUsedAt) {
      byKey.set(key, e);
    }
  }
  return { entries: [...byKey.values()], merged };
}

function sanitizeUnknownTopLevel(raw: Record<string, unknown>): { stripped: Record<string, unknown>; removed: string[] } {
  const allowed = new Set(['version', 'entries']);
  const removed: string[] = [];
  const stripped: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (allowed.has(k)) stripped[k] = v;
    else removed.push(k);
  }
  return { stripped, removed };
}

function parseAndHealEntries(rawEntries: unknown, heal: ShareJsonHealReport): ShareCacheEntry[] {
  if (!Array.isArray(rawEntries)) {
    pushHeal(heal, 'entries_sanitized', 'entries was not an array — replaced with [].');
    return [];
  }
  const out: ShareCacheEntry[] = [];
  let dropped = 0;
  for (const row of rawEntries) {
    const one = shareJsonFileSchema.shape.entries.element.safeParse(row);
    if (one.success) {
      out.push(one.data as ShareCacheEntry);
    } else {
      dropped += 1;
    }
  }
  if (dropped > 0) {
    pushHeal(
      heal,
      'entries_sanitized',
      dropped === 1 ? 'Dropped 1 invalid share.json entry.' : `Dropped ${String(dropped)} invalid share.json entries.`,
    );
  }
  const { entries, merged } = mergeDuplicateShareEntries(out);
  if (merged > 0) {
    pushHeal(
      heal,
      'duplicates_merged',
      merged === 1 ? 'Merged 1 duplicate share cache row (same worker id).' : `Merged ${String(merged)} duplicate share cache rows.`,
    );
  }
  return entries;
}

function coerceShareFileFromUnknown(parsed: unknown, heal: ShareJsonHealReport): ShareJsonFile {
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    pushHeal(heal, 'invalid_json', 'Root JSON was not an object — replaced with empty share file.');
    return emptyShareFile();
  }
  const raw = parsed as Record<string, unknown>;
  const { stripped, removed } = sanitizeUnknownTopLevel(raw);
  if (removed.length > 0) {
    pushHeal(
      heal,
      'entries_sanitized',
      `Removed unknown top-level share.json fields: ${removed.sort().join(', ')}`,
    );
  }
  const ver = stripped.version;
  if (ver !== 1) {
    pushHeal(
      heal,
      'version_reset',
      `share.json version was ${String(ver)} — reset to version 1 (only v1 is supported today).`,
    );
  }
  const entries = parseAndHealEntries(stripped.entries, heal);
  const candidate: ShareJsonFile = { version: 1, entries };
  const checked = shareJsonFileSchema.safeParse(candidate);
  if (!checked.success) {
    pushHeal(heal, 'entries_sanitized', `share.json failed final validation — cleared entries (${checked.error.message}).`);
    return emptyShareFile();
  }
  return checked.data;
}

function backupCorruptShareFile(sharePath: string, runtime: CacheRuntime): void {
  const dir = runtime.path.dirname(sharePath);
  const stamp = String(runtime.system.now());
  const bak = runtime.path.join(dir, `share.json.bak.${stamp}.json`);
  try {
    const raw = assertSyncPortResult(runtime.fs.readText(sharePath), 'fs.readText', sharePath);
    assertSyncPortResult(runtime.fs.mkdirp(dir), 'fs.mkdirp', dir);
    assertSyncPortResult(runtime.fs.writeText(bak, raw), 'fs.writeText', bak);
    assertSyncPortResult(runtime.fs.deleteFile(sharePath), 'fs.deleteFile', sharePath);
  } catch {
    /* best-effort backup */
  }
}

/**
 * Loads `share.json` with self-heal: never throws; returns issues when repair occurred.
 */
export function loadShareJsonFile(input: {
  sharePath: string;
  runtime: CacheRuntime;
  maxBytes?: number;
}): LoadShareJsonResult {
  const { sharePath, runtime } = input;
  const maxBytes = input.maxBytes ?? DEFAULT_MAX_SHARE_JSON_BYTES;
  const heal = healReport();
  const issues: Issue[] = [];

  const exists = assertSyncPortResult(runtime.fs.exists(sharePath), 'fs.exists', sharePath);
  if (!exists) {
    heal.actions.push('missing_file');
    heal.details.push('share.json was missing — starting with an empty in-memory cache.');
    const file = emptyShareFile();
    return { file, heal, issues };
  }

  const { data, warning } = readJsonFileWithLimit<unknown>(sharePath, maxBytes, runtime);
  if (warning?.code === 'cache_oversize') {
    backupCorruptShareFile(sharePath, runtime);
    pushHeal(heal, 'oversized_file', warning.message);
    const file = emptyShareFile();
    issues.push(shareJsonRepairedIssue(heal, sharePath));
    return { file, heal, issues };
  }

  if (warning?.code === 'cache_malformed' || warning?.code === 'cache_io_error') {
    backupCorruptShareFile(sharePath, runtime);
    pushHeal(
      heal,
      'invalid_json',
      warning.message.includes('cache read') ? warning.message : `Invalid share.json: ${warning.message}`,
    );
    const file = emptyShareFile();
    issues.push(shareJsonRepairedIssue(heal, sharePath));
    return { file, heal, issues };
  }

  if (data === undefined) {
    const file = emptyShareFile();
    return { file, heal, issues };
  }

  const file = coerceShareFileFromUnknown(data, heal);
  if (heal.repaired) {
    issues.push(shareJsonRepairedIssue(heal, sharePath));
  }
  return { file, heal, issues };
}

export type SaveShareJsonResult = {
  warning?: Issue;
};

/**
 * Writes `share.json` atomically when the cache runtime allows writes.
 */
export function saveShareJsonFile(input: {
  sharePath: string;
  file: ShareJsonFile;
  runtime: CacheRuntime;
}): SaveShareJsonResult {
  const { sharePath, file, runtime } = input;
  const warn = writeJsonAtomic(sharePath, file, runtime);
  if (!warn) return {};
  return {
    warning: {
      severity: 'warning',
      code: ISSUE_SHARE_JSON_WRITE_FAILED,
      message: warn.message,
      path: sharePath,
    },
  };
}

/**
 * Byte length of serialized `share.json` (UTF-8) for diagnostics.
 */
export function shareJsonSerializedByteLength(file: ShareJsonFile, runtime: CacheRuntime): number {
  return textByteLength(JSON.stringify(file, null, 2), runtime);
}
